[package]
name = "mavlink-camera-manager"
version = "0.2.1"
description = "Mavlink Camera Manager"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

readme = "README.md"
documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
path = "src/main.rs"
name = "mavlink-camera-manager"

[dependencies]
clap = "2"
pnet = "0.25"
regex = "1.3"

## Mavlink
mavlink = { git = "https://github.com/patrickelectric/rust-mavlink", branch = "broadcast", features = ["default", "emit-extensions"] }

## RTSP server
failure = { version = "0.1", optional = true }
failure_derive = { version = "0.1", optional = true }
glib = { version = "0.9", optional = true }
gstreamer = { version = "0.15", optional = true }
gstreamer-rtsp-server = { version = "0.15", optional = true }

[features]
"rtsp" = ["failure", "failure_derive", "glib", "gstreamer", "gstreamer-rtsp-server"]
default = []