[package]
name = "mavlink-camera-manager"
version = "0.2.4"
description = "Mavlink Camera Manager"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

readme = "README.md"
documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

default-run = "mavlink-camera-manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
name = "mavlink-camera-manager"
path = "src/main_command_line.rs"

[[bin]]
bench = false
name = "mavlink-camera-manager-web-service"
path = "src/main_web_service.rs"
required-features = ["rtsp"]

[dependencies]
clap = "2"
toml = { version = "0.5.6", features = ["preserve_order"] }
pnet = "0.25"
regex = "1.3"

actix-web = "1.0.9"
serde_derive = "^1.0.8"
serde = "^1.0.8"
serde_json = "^1.0.41"
notify = "4.0.15"
derivative = "2.1.1"

## Mavlink
mavlink = { version = "0.8.2", features = ["default", "emit-extensions"] }

## RTSP server
glib = { version = "0.9", optional = true }
gstreamer = { version = "0.15", optional = true }
gstreamer-rtsp-server = { version = "0.15", optional = true }

[dev-dependencies]
rand = "0.7"

[features]
gst = ["glib", "gstreamer"]
rtsp = ["gst", "gstreamer-rtsp-server"]
default = []
