on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v1.0.8
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt update
            apt search gst
            apt install -y curl
            apt install -y gstreamer1.0-rtsp libavahi-glib-dev libavahi-core-dev
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
            export PATH="$HOME/.cargo/bin:$PATH"
            cargo build --features rtsp

      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"