name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libraries
      run: sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-dev
    - name: Check style
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose --features=rtsp
    - name: Run tests
      run: |
        cargo test --verbose
    - name: Cargo publish
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cargo package
        [[ "$(git describe --tags)" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] && cargo publish --allow-dirty --token $TOKEN || echo "No tag availale for this commit."

